# Generated by Django 4.2.5 on 2023-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Топливо')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за литр')),
            ],
        ),
    ]
