# Generated by Django 4.2.5 on 2023-09-16 18:00

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ordersList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.AlterField(
            model_name='fuel',
            name='type',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Топливо'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('carModel', models.CharField(max_length=50, verbose_name='Модель машины')),
                ('carColor', models.CharField(max_length=50, verbose_name='Цвет машины')),
                ('carNumber', models.CharField(max_length=10, verbose_name='Номер машины')),
                ('volume', models.IntegerField(verbose_name='Объем')),
                ('totalPrice', models.IntegerField(blank=0, verbose_name='Объем')),
                ('paymentMethod', models.CharField(choices=[('cash', 'Наличные'), ('credit_card', 'Банковская карта'), ('bank_transfer', 'Онлайн перевод'), ('fuel_card', 'Топливная карта')], max_length=20, verbose_name='Способ оплаты')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersList.city')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersList.fuel')),
            ],
        ),
    ]
