# Generated by Django 4.2.5 on 2023-09-16 18:33

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ordersList', '0002_city_alter_fuel_type_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['timeCreate', 'timeDeparture'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='timeCreate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='timeDeparture',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
