# Generated by Django 4.2.5 on 2023-09-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersList', '0003_alter_order_options_order_timecreate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeCreate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeDeparture',
            field=models.DateTimeField(verbose_name='Время доставки'),
        ),
    ]
