# Generated by Django 4.2.5 on 2023-09-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersList', '0005_alter_order_city_alter_order_fuel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'verbose_name': 'Топливо', 'verbose_name_plural': 'Топливо'},
        ),
    ]
