# Generated by Django 4.2.5 on 2023-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersList', '0007_alter_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isDone',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
