# Generated by Django 4.2.5 on 2023-09-16 20:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ordersList', '0008_order_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заказа'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('carModel', models.CharField(max_length=50, verbose_name='Модель машины')),
                ('carColor', models.CharField(max_length=50, verbose_name='Цвет машины')),
                ('carNumber', models.CharField(max_length=10, verbose_name='Номер машины')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersList.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
    ]
